version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
  fake_api:
    image: jaxgeller/lwan
    volumes:
      - ./data:/lwan/wwwroot
    ports:
      - "8000:8080"
  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
  kraken_designer:
    image: devopsfaith/krakendesigner:latest
    ports:
      - 8787:80
  krakend_ce:
    image: devopsfaith/krakend:0.9.0
    volumes:
      - ./krakend:/etc/krakend
    ports:
      - "8080:8080"
      - "8090:8090"
    depends_on:
      - fake_api
      - jaeger
